const userConst = {
     SIGNUP_REQUEST : "SIGNUP_REQUEST",
     SIGNUP_SUCCESS : "SIGNUP_SUCCESS", 
     SIGNUP_FAILURE : "SIGNUP_FAILURE",
     SIGNIN_REQUEST : "SIGNIN_REQUEST",
     SIGNIN_SUCCESS : "SIGNIN_SUCCESS", 
     SIGNIN_FAILURE : "SIGNIN_FAILURE",
     UPDATE_REQUEST : "UPDATE_REQUEST",
     UPDATE_SUCCESS : "UPDATE_SUCCESS", 
     UPDATE_FAILURE : "UPDATE_FAILURE",
     SIGNOUT : "SIGNOUT",
     SIGNOUT_FAILURE : "SIGNOUT_FAILURE"
}

export default userConst;