const productConst = {
    PRODUCTCOLLECTION_REQUEST : "PRODUCTCOLLECTION_REQUEST",
    PRODUCTCOLLECTION_SUCCESS : "PRODUCTCOLLECTION_SUCCESS", 
    PRODUCTCOLLECTION_FAILURE : "PRODUCTCOLLECTION_FAILURE",
    CREATPRODUCT_REQUEST : "CREATPRODUCT_REQUEST",
    CREATPRODUCT_SUCCESS : "CREATPRODUCT_SUCCESS", 
    CREATPRODUCT_FAILURE : "CREATPRODUCT_FAILURE",
    UPDATEPRODUCT_REQUEST : "UPDATEPRODUCT_REQUEST",
    UPDATEPRODUCT_SUCCESS : "UPDATEPRODUCT_SUCCESS", 
    UPDATEPRODUCT_FAILURE : "UPDATEPRODUCT_FAILURE",
    DELETEPRODUCT_REQUEST : "DELETEPRODUCT_REQUEST",
    DELETEPRODUCT_SUCCESS : "DELETEPRODUCT_SUCCESS", 
    DELETEPRODUCT_FAILURE : "DELETEPRODUCT_FAILURE",    
}

export default productConst;