const orderConst = {
    ORDERCOLLECTION_REQUEST : "ORDERCOLLECTION_REQUEST",
    ORDERCOLLECTION_SUCCESS : "ORDERCOLLECTION_SUCCESS", 
    ORDERCOLLECTION_FAILURE : "ORDERCOLLECTION_FAILURE",
    CREATORDER_REQUEST : "CREATORDER_REQUEST",
    CREATORDER_SUCCESS : "CREATORDER_SUCCESS", 
    CREATORDER_FAILURE : "CREATORDER_FAILURE",
    UPDATEORDER_REQUEST : "UPDATEORDER_REQUEST",
    UPDATEORDER_SUCCESS : "UPDATEORDER_SUCCESS", 
    UPDATEORDER_FAILURE : "UPDATEORDER_FAILURE",
    DELETEORDER_REQUEST : "DELETEORDER_REQUEST",
    DELETEORDER_SUCCESS : "DELETEORDER_SUCCESS", 
    DELETEORDER_FAILURE : "DELETEORDER_FAILURE",   
    DISCONNECT : "DISCONNECT",
    DISCONNECT_FAILURE : "DISCONNECT_FAILURE",
}

export default orderConst;